### ISSUE TITLE
Android native plugin doesn't support AGP 8.0

### ISSUE THREAD

**Issue by dkrutskikh** [fingerprintjs/fingerprintjs-pro-flutter#52]
Android Flutter plugins should add namespace under android inside the build configuration for the app.
Something like [this](https://github.com/fluttercommunity/plus_plugins/pull/1704/files).

Steps to reproduce

- Create a new Flutter Application (empty)
- Use Android Studio's "AGP Upgrade Assistant" to upgrade to Gradle 8
- flutter pub add fpjs_pro_plugin

Also check official android documentation [here](https://developer.android.com/build/publish-library/prep-lib-release#choose-namespace).

**Comment by ilfa** [comment]
Thank you for the issue!

Looks like we will fix it by tomorrow.

**Comment by ilfa** [comment]
We still need some tome to test it, but you already can try [2.0.2-test.1](https://pub.dev/packages/fpjs_pro_plugin/versions/2.0.2-test.1) prerelease and give us a feedback.

**Comment by ilfa** [comment]
We finally published the version [2.0.2](https://github.com/fingerprintjs/fingerprintjs-pro-flutter/releases) with the fix for Gradle.

Thank you @dkrutskikh for the issue.
And thank you @vant3ch for the contribution!
