### ISSUE TITLE
Error running while using the extendedResponseFormat set to true.

### ISSUE THREAD

**Issue by JJordani** [fingerprintjs/fingerprintjs-pro-flutter#72]
Hello guys, I hope I could get some help wto identify the issue I'm running into.

### Description

When trying to get VisitorData while using the extendedResponseFormat set to true, I receive an error stating `Null is not a subtype of Map<dynamic, dynamic>`. This error occurs both when importing the library into my own project and when running the example project provided by the library.

### Steps to Reproduce

1. Import the fpjs_pro_plugin library into your project or run the example project.
2. Call the initializer (initFpjs) with extendedResponseFormat set to true.
3. Call the getVisitorData function
4. Run the application.

### Error

The log show the following error and stack:
```
Unhandled Exception: type 'Null' is not a subtype of type 'Map<dynamic, dynamic>'
#0      new FingerprintJSProExtendedResponse.fromJson (package:fpjs_pro_plugin/result.dart:83:63)
#1      FpjsProPlugin.getVisitorData (package:fpjs_pro_plugin/fpjs_pro_plugin.dart:89:46)
<asynchronous suspension>
#2      _MyAppState._getDeviceData (package:fpjs_pro_plugin_example/main.dart:109:26)
<asynchronous suspension>
#3      _ExtendedResultDialog.build.<anonymous closure>.<anonymous closure> (package:fpjs_pro_plugin_example/main.dart:185:35)
<asynchronous suspension>

``` 

### Environment

- Library version: 3.0.0
- Test Devices: iPhone16,1 running iOS 17.5.1, Android emulator
- Flutter Doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.5 23F79 darwin-x64, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.91.1)
[✓] Connected device (6 available)
[✓] Network resources
```

**Comment by JJordani** [comment]
Do you mean the `FpjsProPlugin.initFpjs` call?

I just called it with the token and extendedResponseFormat. I'm not using proxy integrations as I was initially only testing mobile.
```
  Future<void> _initFpjs(String apiToken) async {
    await FpjsProPlugin.initFpjs(apiToken, extendedResponseFormat: true);
  }
```

**Comment by makma** [comment]
Yes, I meant that, thx, should be enough for now. We'll reach back once we investigate.
